### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by PCAssistSoftware** [becerda/DiskpartGUI-WPF#36]
Hi
Firstly this is a great project, really like your work

Can I ask a couple of questions please:-

1) Why does Format button only enable for Removable drives? can I change this?

2) Why do I get error when trying to "clear read-only" on a drive where it is shown as set - see image below

Thanks

![diskpart1](https://user-images.githubusercontent.com/10872799/64067600-2c42ae80-cc23-11e9-874b-0e17f38acd99.png)

**Comment by becerda** [comment]
I am glad you are liking this project. I'd be happy to answer your questions.

1) This project is a clone of another made in Java. The original business rules stated that only removable drives should be formated. I can add an option to allow formatting of all drive types. Thank you for that suggestion.

2) Thanks for showing me this issue. I will add some more logging info to find the source. Once pushed would you be able to run again and send this info?

**Comment by PCAssistSoftware** [comment]
Excellent - thank you.

Yes let me know when you have made a change and I would be more than willing to do any testing you need to help

**Comment by PCAssistSoftware** [comment]
I think it has something to do with the disk numbers being shown in list not equating to what is shown if you run diskpart manually in command prompt - see screenshot below where it thinks my external drive is number 7, but in reality in diskpart command line it is number 3.  So it needs to count from 0 and not count those with drive letters as they are part of same disk?

![diskpart2](https://user-images.githubusercontent.com/10872799/64069889-ecdc8800-cc4b-11e9-9133-9a1eb1219789.png)

**Comment by PCAssistSoftware** [comment]
I think (and I may be wrong) but some parts of the code access VOLUME e.g. LIST VOLUME, but then for reading and setting read-only flag it is using LIST DISK  / SELECT DISK, so the driver number is different.  Screenshot below shows same computer as above but using List Volume compared to List Disk in DiskPart command line


![image](https://user-images.githubusercontent.com/10872799/64069931-b6533d00-cc4c-11e9-92ed-76dd929c5cba.png)

**Comment by PCAssistSoftware** [comment]
apologies for all the replies but I keep trying things out so wanted to report back to help

The list above from app shows it is missing Volume 0 D  DVD-ROM so that is why # column starts from 1 not 0 like it should.  It also misses Volume 6   ESP  FAT32 for some reason and also Volume 8 F  

So even if you change SELECT DISK and ATTRIBUTE DISK to SELECT VOLUME and ATTRIBUTE VOLUME in "public ProcessExitCode GetReadOnlyState(ref List<Volume> volumes)" it doesn't work as it is looking at wrong volume numbers as needs to start from 0

**Comment by becerda** [comment]
Yes, thank you! So again, the original business rules just delt with removable thumb drives and it was easier set the read only flags with the associated disk. I am in the middle of an update that will allow the user to show both Volumes and Disks, one at a time. With this update it will split the functionality using the correct command for either Volume or Disk.

No worries about all the comments. They are appreciated and helpful!

**Comment by PCAssistSoftware** [comment]
nice one - look forward to testing it for you

**Comment by becerda** [comment]
I have pushed the update to the development branch. The ability to switch between volumes and disks has been implemented. 

View > Show Volumes/Disks. 

You can also right click and select Show Volumes/Disks. There are some known issues with the Disk side of things but should still work. This might resolve some of the issues you were having. 

Notes:
1. Diskpart only allows certain volumes to set their read-only flag. I don't know what those volumes are, however I know what volumes cannot be set. It is implemented based on the volumes I know cannot be set. Same goes for Disks.

2. Diskpart also only allows certain volumes to be formatted. Same rules as before. Implemented based on what I know cannot be formatted.

I have also updated the regex to find volumes and disks, hopefully it finds those missing volumes.

**Comment by PCAssistSoftware** [comment]
Hi

Thanks for making the changes.

I can confirm that the Show Volumes now correctly lists all my volumes :)

Show Disk currently crashes for me at the point of return gpt[type]; (Line 293 BaseMedia.cs) with error "System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'"
I think it is because the value it is finding is * as can be seen in my DiskPart list disk screenshot above.

Still getting odd results for ReadOnly column though, as you can see from screenshot below it thinks number 7 is readonly, but looking at it in DiskPart command line it is not?

![image](https://user-images.githubusercontent.com/10872799/64076073-f4d21180-ccb7-11e9-99dc-f067b6252072.png)

**Comment by becerda** [comment]
Not quite sure what was going on with those incorrect set read only flags. I have changed the layout just a bit though. Instead of only showing the read only flag, all the flags will be shown in the last column.

The KeyNotFoundException should be fixed. You were correct, diskpart displays it as a '*' and this was not in the look up dictionary.

**Comment by PCAssistSoftware** [comment]
Excellent thanks for letting me know, it now works perfectly fine for both Volumes and Disks, ReadOnly now appears correctly, and as you say the other error is fixed and the GPT column shows correctly

I really like how you use RegEx in this app, it is something I have been learning and using a lot recently, but never knew you could give a name/reference to each value you find with RegEx and then access them later e.g. ?<volnum> and ?<vollab> etc, that is very useful and something I will ready up on

Thank you

**Comment by becerda** [comment]
Awesome! Glad to hear it is working and glad that you are learning something from this project. I am planning on implementing more features in the future, if and when the come out it would be awesome if you could test them. For now I am closing this issue.

**Comment by PCAssistSoftware** [comment]
I would definitely be interested in testing any new features you add, I am "watching" the project so should get notified of changes, but if not just re-open and reply to this comment and I will test anything you need testing :)

**Comment by PCAssistSoftware** [comment]
Could you possibly tell me what line(s) of code to modify so I can Format all disks and not just removable please?

**Comment by becerda** [comment]
That is next on my to-do list but a quick and dirty way would be to go into the Volume.cs file and have the method IsValid() return true. Be aware that this may have some unintended side effects. 

Also, as mentioned before diskpart can only format volumes, not disks, and specific volumes at that.

**Comment by PCAssistSoftware** [comment]
Thank you, I will give it a try

DiskPart can format disks as well I believe as I use a script like below passed to DiskPart to create and format partitions before restoring images to them

`select disk 0
clean
convert gpt
rem == 1. System partition =========================
create partition efi size=100
format quick fs=fat32 label="System"
assign letter="S"
rem == 2. Microsoft Reserved (MSR) partition =======
create partition msr size=16
rem == 3. Windows partition ========================
rem ==    a. Create the Windows partition ==========
create partition primary 
rem ==    b. Create space for the recovery tools ===
shrink minimum=500
rem ==    c. Prepare the Windows partition ========= 
format quick fs=ntfs label="Windows"
assign letter="W"
rem === 4. Recovery tools partition ================
create partition primary
format quick fs=ntfs label="Recovery tools"
assign letter="R"
set id="de94bba4-06d1-4d40-a16a-bfd50179d6ac"
gpt attributes=0x8000000000000001
list volume
exit`

Sorry the above lost its formatting, but in essence I select disk - and then can partition and FORMAT them so assume it works with disks and volumes?

**Comment by becerda** [comment]
So a disk is what holds volumes or paritions. A disk can have multiple volumes or partitions. This script basically deletes all volumes and partitions on disk 0. Creates what looks like several partitions on it: a system partition, a reserved partition, a primary partition, and a recovery partition. Every time 'create partiton' is called it is automatically selecting the newly created one, which you should be selecting manually for safety reasons. Then format is being called on that partition.

The format operations are being preformed on the partitions not the disks.

**Comment by PCAssistSoftware** [comment]
That makes complete sense, and as I was typing it I had sort of got it in my head anyway - but thanks for clarifying.  I meant partitions really as I was selecting disk and then creating new partitions to format.  Just a moment of confusion when you said only volumes can be formatted.  Thanks

**Comment by PCAssistSoftware** [comment]
"Also, as mentioned before diskpart can only format volumes"

So for anyone else reading this later - diskpart can format volumes AND partitions

**Comment by PCAssistSoftware** [comment]
suggestion:-

Change:-

public string DriveLetter
{
    get
    {
        return Letter + ":";
    }
}

To

public string DriveLetter
{
    get
    {
        if (DriveLetter != null)
            return Letter + ":";
        else
            return Letter;
    }
}

or similar so that for drives that have no letter assigned it shows blank in column rather than :
