### ISSUE TITLE
suggestion: ability to show Disk # as well when viewing volumes

### ISSUE THREAD

**Issue by PCAssistSoftware** [becerda/DiskpartGUI-WPF#41]
It is often very handy to be able to work out what partitions are on which particular drive, especially if formatting or applying an image etc.

For example with the volume view I can see my Z: drive as per screenshot, but I don't know what physical drive it is located on.

![image](https://user-images.githubusercontent.com/10872799/64200241-fea87000-ce83-11e9-9735-e7d788b50a03.png)

Yes I could change to disk view and go by the size, but if you have several drives all the same size then it is easy to select the wrong one to wipe or apply an image to.

I have spent a while this afternoon working out how you can map a drive letter to the physical drive ID it is located on.  Now you may come up with a better way, but I tried initially with WMI and then found a better solution with PowerShell.  So as per my mocked up version below as well as showing Volume # it now also shows Disk # for all volumes which a) have a drive letter and b) are not showing No Media.  So you can see drive letter Z: is on Disk 0 which is confirmed if looking in Disk Management

![image](https://user-images.githubusercontent.com/10872799/64200427-6959ab80-ce84-11e9-8335-1609cf16d9ed.png)

![image](https://user-images.githubusercontent.com/10872799/64200456-77a7c780-ce84-11e9-94c5-47a5fed7eb1a.png)

Just an idea for future..... :)

**Comment by becerda** [comment]
This is a good idea. I'll look into how to implement it using diskpart commands first, then powershell if it cannot be done.

**Comment by PCAssistSoftware** [comment]
Cool.  Let us know how you get on - I have a fully working prototype using PowerShell to retrieve the results needed which I can provide if needed.  It is in VB but can soon convert it to C# for you

**Comment by PCAssistSoftware** [comment]
N.B. I also now have a working WMI solution in VB that does same thing - so either are an option if can't be done directly with diskpart commands

**Comment by becerda** [comment]
Sorry it took so long to get this worked out. I've been going back and forth on how I wanted to implement this. I decided I would go ahead and pull all the details of the disks, volumes, and partitions.

The Disk header has been added to both the volumes list and the partitions list. If you find any bugs with this, which I'm sure I missed some, please open another issue thread.
