### ISSUE TITLE
FIX: RegEx for volumes missing drives with numbers in label

### ISSUE THREAD

**Issue by PCAssistSoftware** [becerda/DiskpartGUI-WPF#42]
It doesn't show any drives which have numbers in the volume label

Change

Private Const Volume_Parse_RX As String = "Volume (?<volnum>[0-9]+){1,2}( ){4,5}(?<vollet>[A-Z ])( ){0,3}(?<vollab>[a-zA-Z ]{0,11})( ){2,3}(?<volfs>NTFS|FAT32|exFAT|CDFS|UDF)?( ){2,7}(?<voltype>Partition|Removable|DVD-ROM|Simple)?( ){3,14}(?<volsize>[0-9]{1,4})?( )(?<volgk>K|G|M)?B( ){2}(?<volstat>Healthy|No Media)?( ){0,11}(?<volinfo>[a-zA-Z]+)?"
	

to

Private Const Volume_Parse_RX As String = "Volume (?<volnum>[0-9]+){1,2}( ){4,5}(?<vollet>[A-Z ])( ){0,3}(?<vollab>[a-zA-Z**0-9** ]{0,11})( ){2,3}(?<volfs>NTFS|FAT32|exFAT|CDFS|UDF)?( ){2,7}(?<voltype>Partition|Removable|DVD-ROM|Simple)?( ){3,14}(?<volsize>[0-9]{1,4})?( )(?<volgk>K|G|M)?B( ){2}(?<volstat>Healthy|No Media)?( ){0,11}(?<volinfo>[a-zA-Z]+)?"

**Comment by becerda** [comment]
Pushed updated regex to development.
Thank you!

**Comment by PCAssistSoftware** [comment]
further to this - it might be worth amending that same RegEx to include all the allowed characters that can be used for volume labels, as when renaming a volume you have RegEx to check they are allowed characters but if you use say a _ in a volume it then doesn't get picked up when listing the volumes
